apiVersion: batch/v1
kind: Job
metadata:
  name: batch-check-job
spec:
  template:
    metadata:
      name: batch-check-job
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-node01
      containers:
        - name: batch-check
          image: madhuakula/k8s-goat-batch-check
          imagePullPolicy: IfNotPresent
          # command:
          #  - "bin/sh"
          #  - "-c"
          #  - "htop"
      restartPolicy: Never
